"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os, sys, shutil

# Setup/user input
if "-A" in sys.argv:
    devBuild = True
else:
    devBuild = True if input("Dev Build? [DevBuild doesn't bundle Python and doesn't make the disk image] y/n: ").lower()=="y" else False

version = input("Version string: ")

# Remove old build files
try:
    shutil.rmtree("dist")
    shutil.rmtree("build")
    os.remove("Battery Control.dmg")
except:
    pass

# Build the app with py2app
APP = ['Battery.py']
DATA_FILES = []
OPTIONS = {
        "iconfile":'icon.icns',
        "alias":devBuild,
        "plist":{
            "CFBundleGetInfoString": "MacOS Battery Control GUI",
            "CFBundleShortVersionString":version,
            "CFBundleVersion":version,
            "NSHumanReadableCopyright":"Copyright oliver408i (c) © 2023",
            "CFBundleIdentifier":"tech.rufan.batteryapp"
        }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

# Debugging purposes
#os.rename("dist/Battery.app",f"dist/Battery {version}.app")

# Make the dmg
if not devBuild:
    os.system("""create-dmg --volname "Battery Control" --volicon "icon.icns" --window-pos 200 120 --window-size 800 400 --icon-size 100 --icon "Battery.app" 200 190 --hide-extension "Battery.app" --app-drop-link 600 185 "Battery Control.dmg" "dist" """)
