"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os, sys, shutil

if "-A" in sys.argv:
    devBuild = True
else:
    devBuild = True if input("Dev Build? [DevBuild doesn't bundle Python and doesn't make the disk image] y/n: ").lower()=="y" else False

version = input("Version string: ")

shutil.rmtree("dist")
shutil.rmtree("build")

APP = ['Battery.py']
DATA_FILES = []
OPTIONS = {
        "iconfile":'icon.icns',
        "alias":devBuild,
        "plist":{
            "CFBundleGetInfoString": "MacOS Battery Control GUI",
            "CFBundleShortVersionString":version,
            "CFBundleVersion":version,
            "NSHumanReadableCopyright":"Copyright (c) © 2023"
        }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

os.rename("dist/Battery.app",f"dist/Battery {version}.app")

if not devBuild:
    os.system("""create-dmg --volname "Battery Control" --volicon "icon.icns" "Battery Control.dmg" "dist" """)
